# Form implementation generated from reading ui file 'frmKitchenView.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmKitchenView(object):
    def setupUi(self, frmKitchenView):
        frmKitchenView.setObjectName("frmKitchenView")
        frmKitchenView.resize(980, 500)
        frmKitchenView.setStyleSheet("background-color: rgb(10, 16, 30);")
        self.centralwidget = QtWidgets.QWidget(parent=frmKitchenView)
        self.centralwidget.setObjectName("centralwidget")
        self.lblLogo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLogo.setGeometry(QtCore.QRect(850, 0, 121, 81))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("../Images/AlaturkaPlain.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.lblUsername = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblUsername.setGeometry(QtCore.QRect(0, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblUsername.setFont(font)
        self.lblUsername.setStyleSheet("color: rgb(230, 230, 230);")
        self.lblUsername.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblUsername.setObjectName("lblUsername")
        self.lstOrderView = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstOrderView.setGeometry(QtCore.QRect(10, 100, 951, 271))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lstOrderView.setFont(font)
        self.lstOrderView.setStyleSheet("color: rgb(255, 255, 255);")
        self.lstOrderView.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lstOrderView.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lstOrderView.setLineWidth(5)
        self.lstOrderView.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.lstOrderView.setObjectName("lstOrderView")
        self.btnBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnBack.setGeometry(QtCore.QRect(10, 440, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btnBack.setFont(font)
        self.btnBack.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(132, 116, 77);")
        self.btnBack.setObjectName("btnBack")
        self.btnComplete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnComplete.setGeometry(QtCore.QRect(370, 390, 241, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btnComplete.setFont(font)
        self.btnComplete.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(132, 116, 77);")
        self.btnComplete.setObjectName("btnComplete")
        self.btnRefresh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnRefresh.setGeometry(QtCore.QRect(850, 440, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btnRefresh.setFont(font)
        self.btnRefresh.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(132, 116, 77);")
        self.btnRefresh.setObjectName("btnRefresh")
        frmKitchenView.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=frmKitchenView)
        self.statusbar.setObjectName("statusbar")
        frmKitchenView.setStatusBar(self.statusbar)

        self.retranslateUi(frmKitchenView)
        QtCore.QMetaObject.connectSlotsByName(frmKitchenView)

    def retranslateUi(self, frmKitchenView):
        _translate = QtCore.QCoreApplication.translate
        frmKitchenView.setWindowTitle(_translate("frmKitchenView", "Kitchen View"))
        self.lblUsername.setText(_translate("frmKitchenView", "username"))
        self.lstOrderView.setSortingEnabled(True)
        self.btnBack.setText(_translate("frmKitchenView", "BACK"))
        self.btnComplete.setText(_translate("frmKitchenView", "COMPLETED"))
        self.btnRefresh.setText(_translate("frmKitchenView", "REFRESH"))
