# Form implementation generated from reading ui file 'frmLogin.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmLogin(object):
    def setupUi(self, frmLogin):
        frmLogin.setObjectName("frmLogin")
        frmLogin.resize(345, 396)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmLogin.sizePolicy().hasHeightForWidth())
        frmLogin.setSizePolicy(sizePolicy)
        frmLogin.setStyleSheet("background-color: rgb(10, 16, 30);")
        self.centralwidget = QtWidgets.QWidget(parent=frmLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(90, 30, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(52)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("color: rgb(137, 123, 75);")
        self.lblTitle.setScaledContents(False)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.txtUsername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtUsername.setGeometry(QtCore.QRect(50, 170, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtUsername.setFont(font)
        self.txtUsername.setStyleSheet("color: rgb(255, 255, 255);")
        self.txtUsername.setInputMask("")
        self.txtUsername.setPlaceholderText("")
        self.txtUsername.setObjectName("txtUsername")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtPassword.setGeometry(QtCore.QRect(50, 240, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtPassword.setFont(font)
        self.txtPassword.setStyleSheet("color: rgb(225, 225, 225);")
        self.txtPassword.setInputMask("")
        self.txtPassword.setText("")
        self.txtPassword.setPlaceholderText("")
        self.txtPassword.setObjectName("txtPassword")
        self.btnLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(110, 330, 113, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLogin.sizePolicy().hasHeightForWidth())
        self.btnLogin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(145, 129, 83);")
        self.btnLogin.setAutoDefault(False)
        self.btnLogin.setDefault(False)
        self.btnLogin.setObjectName("btnLogin")
        frmLogin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=frmLogin)
        self.statusbar.setObjectName("statusbar")
        frmLogin.setStatusBar(self.statusbar)

        self.retranslateUi(frmLogin)
        QtCore.QMetaObject.connectSlotsByName(frmLogin)

    def retranslateUi(self, frmLogin):
        _translate = QtCore.QCoreApplication.translate
        frmLogin.setWindowTitle(_translate("frmLogin", "ALATURKA"))
        self.lblTitle.setText(_translate("frmLogin", "LOGIN"))
        self.btnLogin.setText(_translate("frmLogin", "Log-in"))
