# Form implementation generated from reading ui file 'frmStockReplenishment.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmStockReplenishment(object):
    def setupUi(self, frmStockReplenishment):
        frmStockReplenishment.setObjectName("frmStockReplenishment")
        frmStockReplenishment.resize(980, 500)
        frmStockReplenishment.setStyleSheet("background-color: rgb(10, 16, 30);")
        self.centralwidget = QtWidgets.QWidget(parent=frmStockReplenishment)
        self.centralwidget.setObjectName("centralwidget")
        self.lblLogo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLogo.setGeometry(QtCore.QRect(850, 10, 121, 81))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("../Images/AlaturkaPlain.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.lblUsername = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblUsername.setGeometry(QtCore.QRect(0, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblUsername.setFont(font)
        self.lblUsername.setStyleSheet("color: rgb(230, 230, 230);")
        self.lblUsername.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblUsername.setObjectName("lblUsername")
        self.lstStock = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstStock.setGeometry(QtCore.QRect(330, 150, 291, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lstStock.setFont(font)
        self.lstStock.setStyleSheet("color: rgb(255, 255, 255);")
        self.lstStock.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lstStock.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lstStock.setLineWidth(5)
        self.lstStock.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.lstStock.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.lstStock.setObjectName("lstStock")
        self.btnBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnBack.setGeometry(QtCore.QRect(10, 440, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btnBack.setFont(font)
        self.btnBack.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(132, 116, 77);")
        self.btnBack.setObjectName("btnBack")
        self.lblStockList = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStockList.setGeometry(QtCore.QRect(390, 120, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblStockList.setFont(font)
        self.lblStockList.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblStockList.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblStockList.setObjectName("lblStockList")
        self.btnReorder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnReorder.setGeometry(QtCore.QRect(660, 220, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.btnReorder.setFont(font)
        self.btnReorder.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(132, 116, 77);")
        self.btnReorder.setObjectName("btnReorder")
        frmStockReplenishment.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=frmStockReplenishment)
        self.statusbar.setObjectName("statusbar")
        frmStockReplenishment.setStatusBar(self.statusbar)

        self.retranslateUi(frmStockReplenishment)
        QtCore.QMetaObject.connectSlotsByName(frmStockReplenishment)

    def retranslateUi(self, frmStockReplenishment):
        _translate = QtCore.QCoreApplication.translate
        frmStockReplenishment.setWindowTitle(_translate("frmStockReplenishment", "Stock Replenishment"))
        self.lblUsername.setText(_translate("frmStockReplenishment", "username"))
        self.lstStock.setSortingEnabled(True)
        self.btnBack.setText(_translate("frmStockReplenishment", "BACK"))
        self.lblStockList.setText(_translate("frmStockReplenishment", "Out of Stock"))
        self.btnReorder.setText(_translate("frmStockReplenishment", "Re-Order"))
